### ISSUE TITLE
Criar página de edição de Campo

### ISSUE THREAD

**Issue by amandabezerra** [amandabezerra/treinamento-frontend#3]
## Descrição
Criar página e funcionalidades para editar um Campo.

## Tarefas
- [x] Criar form para editar nome do Campo.
- [x] Criar funcionalidade para excluir Campo.
- [x] Listar as Linhas do Campo.
- [ ] Criar funcionalidades para adicionar e remover Linhas do Campo.
- [x] Garantir que o Campo está sendo editado ou excluído corretamente no backend.

**Comment by aamandafelix** [comment]
### Observações
+ Para simplificar a implementação do projeto, a opção de excluir um Campo ficou presente na tela de edição que é possível ser acessada ao clicar no nome do Campo desejado na listagem ou resultado de pesquisas de Campo.
+ Não foi possível implementar a opção de adicionar e remover Linhas de um Campo na tela de edição a tempo para a release 1.0
