### ISSUE TITLE
Criar página de consulta de Campo

### ISSUE THREAD

**Issue by amandabezerra** [amandabezerra/treinamento-frontend#4]
## Descrição
Criar página e funcionalidades para consultar Campos.

## Tarefas
- [x] Disponibilizar um filtro que permita o filtro pelo campo 'nome' da entidade pai Campo, o preenchimento do campo 'nome' deve ser opcional para a consulta.
- [x] Mostrar resultados da consulta com o nome da entidade pai Campo e a quantidade de filhos Linhas já cadastrados.
- [ ] Disponibilizar opções para editar e para excluir a entidade pai Campo.
- [ ] Ao optar por editar deve ser direcionado para a página de editar Campo.
- [x] Garantir que os resultados refletem corretamente os dados cadastrados no backend.

**Comment by aamandafelix** [comment]
### Observações
+ Para simplificar a implementação do projeto, a opção de editar ficou disponível ao clicar no nome do Campo.
+ Não foi possível implementar a opção de excluir um Campo na tela de consulta a tempo para a release 1.0
